# world-service/Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY world_service.py world_service.py

CMD ["python", "world_service.py"]
