# hello-service/Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY hello_service.py hello_service.py

CMD ["python", "hello_service.py"]
