apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined
  template:
    metadata:
      labels:
        app: combined
    spec:
      containers:
      - name: combined-container
        image: jahnavi268/combined-service:latest
        ports:
        - containerPort: 5002
        
---
apiVersion: v1
kind: Service
metadata:
  name: combined-service
spec:
  selector:
    app: combined
  ports:
  - port: 80
    targetPort: 5002
  type: ClusterIP
